/**
 * Football Stories ("tales") — Mehdi, 2026-09-10.
 * Retention reels (60–90 s) telling a TRUE, strange or memorable football
 * story in 10 animated beats, with a hook in the first 3 seconds, a question
 * for the comments and a like / comment / follow call, in EN, FR and AR.
 * Every story = 3 reels (one per language) + one article on the site (EN + AR).
 *
 * The bank lives in code so every fact stays reviewed by a human before it is
 * published. Add a story = add an entry here (verified facts only: dates,
 * scores, attributed quotes; no tragedy, no living person ridiculed).
 */
export type TaleLang = 'en' | 'fr' | 'ar'
export type TaleVisual =
  | { type: 'mark'; text: string; color?: 'gold' | 'green' }
  | { type: 'scoreboard'; home: string; away: string; hCode: string; aCode: string; hColors: [string, string]; aColors: [string, string]; h: string | number; a: string | number; hl?: 'h' | 'a'; tag?: string }
  | { type: 'pitch'; mode: 'both' | 'one' | 'empty'; top?: string; bottom?: string }
  | { type: 'quote' }
  | { type: 'cta' }
export type TaleBeat = { kicker: string; caption: string; voice: string; visual?: TaleVisual; glow?: 'gold' | 'green'; capSize?: number; min?: number; image?: { query?: string; url?: string; credit?: string; kind?: 'comic' | 'photo' } }
export type TaleText = {
  title: string          // article + reel title
  hook: string           // cover line
  beats: TaleBeat[]
  question: string       // pinned comment question
  caption: string        // Facebook post text: curiosity first, then like / comment / follow
  excerpt: string
  article: string[]      // paragraphs (plain text)
  hashtags: string
  covers?: TaleCover[]   // cover variants (thumbnails) — 1-3 bold lines each (2026-09-16)
  captions?: string[]   // caption variants (one per cover)
}
export type TaleCover = { l1?: string; l2?: string; l3?: string }
export type Tale = { slug: string; year: string; en: TaleText; fr: TaleText; ar: TaleText; needsReview?: string; hold?: boolean; subject?: string; barca?: boolean; comic?: boolean }   // comic: illustrated beats (Gemini) in the paper-frame layout   // needsReview: AI draft whose Arabic failed the checks (audit 2026-09-13)

export const TALE_LABELS: Record<TaleLang, { like: string; comment: string; follow: string; full: string; weekly: string; cta: string; more: string }> = {
  en: { like: 'LIKE', comment: 'COMMENT', follow: 'FOLLOW', full: 'Full story → pressing90.live', weekly: 'New story every day', cta: '➕ Follow Pressing 90 for more incredible football stories.', more: '📖 Full story' },
  fr: { like: "J'AIME", comment: 'COMMENTER', follow: "S'ABONNER", full: "L'histoire complète → pressing90.live", weekly: 'Une nouvelle histoire chaque jour', cta: "➕ Abonne-toi à Pressing 90 pour d'autres histoires incroyables du foot.", more: "📖 L'histoire complète" },
  ar: { like: 'إعجاب', comment: 'تعليق', follow: 'متابعة', full: 'القصة كاملة ← pressing90.live', weekly: 'قصة جديدة كل يوم', cta: '➕ تابع Pressing 90 لمزيد من قصص كرة القدم المذهلة.', more: '📖 القصة كاملة' },
}

const BRB: [string, string] = ['#00267F', '#FFC726'], GRN: [string, string] = ['#CE1126', '#007A5E']
const EST: [string, string] = ['#0072CE', '#111111'], SCO: [string, string] = ['#0065BF', '#FFFFFF']
const sb = (home: string, away: string, hCode: string, aCode: string, hColors: [string, string], aColors: [string, string], h: string | number, a: string | number, hl?: 'h' | 'a', tag?: string): TaleVisual => ({ type: 'scoreboard', home, away, hCode, aCode, hColors, aColors, h, a, hl, tag })

export const TALES: Tale[] = [
  // ───────────────────────────────────────────────────────────────────────
  {
    slug: 'barbados-grenada-1994-own-goal',
    year: '1994',
    en: {
      title: 'The day Barbados scored an own goal to win',
      hook: 'A team scored an own goal on purpose… to win the match.',
      question: '🤔 Would you have scored that own goal? Yes or no, and why? 👇',
      caption: 'They scored an own goal ON PURPOSE. And it worked. 🤯\nThe strangest three minutes in football history, in 90 seconds ⬇️',
      excerpt: 'Caribbean Cup, January 1994: Barbados deliberately scored in their own net, Grenada attacked both goals, and a golden goal counted double. The strangest three minutes in international football.',
      hashtags: '#football #footballstories #didyouknow #Pressing90',
      beats: [
        { kicker: 'DID YOU KNOW?', caption: 'A team scored an\nOWN GOAL on purpose…\nto WIN the match.', voice: 'Did you know… a football team once scored an own goal on purpose… to win the game?', visual: { type: 'mark', text: '?', color: 'green' }, glow: 'gold', capSize: 92, min: 4 },
        { kicker: 'JANUARY 1994', caption: 'Shell Caribbean Cup\nqualifiers', voice: 'January 1994. Caribbean Cup qualifiers. Barbados against Grenada.', visual: sb('BARBADOS', 'GRENADA', 'BRB', 'GRN', BRB, GRN, 0, 0) },
        { kicker: 'THE EQUATION', caption: 'Barbados must win\nby TWO goals.\nOtherwise Grenada\ngoes through.', voice: 'Barbados had to win by two clear goals. Anything less, and Grenada would go through.', capSize: 78 },
        { kicker: '83rd MINUTE', caption: 'Grenada scores.\nBarbados is OUT.', voice: 'Barbados led two–nil. Then, in the eighty-third minute, Grenada scored. Two–one. Barbados was out.', visual: sb('BARBADOS', 'GRENADA', 'BRB', 'GRN', BRB, GRN, 2, 1, 'a') },
        { kicker: 'THE CRAZY RULE', caption: 'A golden goal in extra time\n= TWO goals.', voice: 'But this tournament had a crazy rule: a golden goal in extra time counted as two goals.', visual: { type: 'mark', text: '×2', color: 'gold' }, glow: 'gold' },
        { kicker: '87th MINUTE', caption: 'Barbados scores…\nin their OWN net.', voice: 'So with three minutes left, Barbados did the unthinkable. They turned around… and scored in their own net. Two–two.', visual: sb('BARBADOS', 'GRENADA', 'BRB', 'GRN', BRB, GRN, 2, 2, 'h', 'OWN GOAL') },
        { kicker: '3 SURREAL MINUTES', caption: 'Grenada attacks BOTH goals.\nBarbados defends BOTH goals.', voice: 'Grenada understood instantly: any goal, at either end, would send them through. So Grenada attacked both goals… and Barbados defended both goals. For three surreal minutes.', capSize: 70, visual: { type: 'pitch', mode: 'both', top: 'BARBADOS DEFENDS BOTH', bottom: 'GRENADA ATTACKS BOTH GOALS' } },
        { kicker: "EXTRA TIME · 94'", caption: 'Golden goal. Barbados.\nCounts double: 4–2.', voice: 'Extra time. Fourth minute. Barbados scored the golden goal. It counted double: four–two. Barbados qualified.', visual: sb('BARBADOS', 'GRENADA', 'BRB', 'GRN', BRB, GRN, 4, 2, 'h', 'GOLDEN GOAL'), glow: 'gold' },
        { kicker: "GRENADA'S COACH", caption: '“The person who came up\nwith these rules must be\na candidate for a madhouse.”', voice: "Grenada's coach said: the person who invented these rules must be a candidate for a madhouse.", capSize: 66, visual: { type: 'quote' } },
        { kicker: 'YOUR TURN', caption: 'Would YOU\nhave done the same?', voice: 'Would you have done the same? Tell us in the comments, and follow Pressing 90 for more incredible football stories. Full story on pressing ninety dot live.', visual: { type: 'cta' }, glow: 'gold', min: 10 },
      ],
      article: [
        'On 27 January 1994, in the qualifying group of the Shell Caribbean Cup, Barbados hosted Grenada with a simple-looking task: win by at least two goals to reach the finals. Anything less would send Grenada through instead.',
        'The tournament used a rule that seemed harmless on paper: drawn games went to extra time, and a golden goal in extra time counted as two goals. Nobody had imagined how it could be exploited.',
        'Barbados led 2–0 until the 83rd minute, when Grenada pulled one back. At 2–1 Barbados was winning the match but losing the qualification. Chasing a third goal in the last minutes looked hopeless, so the Barbados players took a decision that still stuns fans today: with three minutes left, they deliberately scored in their own net. At 2–2 the match would go to extra time, where a golden goal would count double and give them the two-goal margin they needed.',
        'Grenada worked it out within seconds. A goal at either end would now qualify them: a normal goal would win the game 3–2, and an own goal would lose it by a single goal, which was enough. So for the final minutes Grenada attacked both goals while Barbados defended both, the strangest passage of play ever seen in an official international match.',
        "Barbados held on, and four minutes into extra time scored the golden goal. Counted as two, the result went down as 4–2, and Barbados qualified. Grenada's coach James Clarkson did not hide his anger: the person who came up with these rules, he said, must be a candidate for a madhouse. The rule was never used again.",
      ],
    },
    fr: {
      title: 'Le jour où la Barbade a marqué contre son camp pour gagner',
      hook: 'Une équipe a marqué contre son camp… exprès. Pour gagner.',
      question: '🤔 Vous auriez marqué ce but contre votre camp ? Oui ou non, et pourquoi ? 👇',
      caption: 'Ils ont marqué contre leur camp EXPRÈS. Et ça a marché. 🤯\nLes trois minutes les plus folles de l\'histoire du foot, en 90 secondes ⬇️',
      excerpt: "Coupe caribéenne, janvier 1994 : la Barbade marque volontairement dans son propre but, Grenade attaque les deux cages, et un but en or compte double. Les trois minutes les plus étranges du football international.",
      hashtags: '#football #histoiredufoot #lesaviezvous #Pressing90',
      beats: [
        { kicker: 'LE SAVIEZ-VOUS ?', caption: 'Une équipe a marqué\n*CONTRE SON CAMP*… exprès.\nPour *GAGNER*.', voice: "Le saviez-vous ? Une équipe de foot a un jour marqué contre son camp… volontairement… pour gagner le match.", visual: { type: 'mark', text: '?', color: 'green' }, glow: 'gold', capSize: 88, min: 4 },
        { kicker: 'JANVIER 1994', caption: 'Qualifications\n*Shell Caribbean Cup*', voice: 'Janvier 1994. Qualifications de la Coupe caribéenne. La Barbade contre Grenade.', visual: sb('BARBADE', 'GRENADE', 'BRB', 'GRN', BRB, GRN, 0, 0) },
        { kicker: "L'ÉQUATION", caption: 'La Barbade doit gagner\npar *DEUX buts* d\'écart.\nSinon, *Grenade* passe.', voice: "La Barbade devait gagner par deux buts d'écart. Sinon, c'est Grenade qui se qualifiait.", capSize: 76 },
        { kicker: '83e MINUTE', caption: '*Grenade* marque.\nLa Barbade est *ÉLIMINÉE*.', voice: 'La Barbade mène deux à zéro. Puis, à la 83e minute, Grenade marque. Deux à un. La Barbade est éliminée.', visual: sb('BARBADE', 'GRENADE', 'BRB', 'GRN', BRB, GRN, 2, 1, 'a') },
        { kicker: 'LA RÈGLE FOLLE', caption: 'Un *but en or* en prolongation\n= *DEUX buts*.', voice: "Mais ce tournoi avait une règle folle : un but en or en prolongation comptait double.", visual: { type: 'mark', text: '×2', color: 'gold' }, glow: 'gold' },
        { kicker: '87e MINUTE', caption: 'La Barbade marque…\ndans *SON PROPRE but*.', voice: "Alors, à trois minutes de la fin, la Barbade fait l'impensable. Elle se retourne… et marque dans son propre but. Deux partout.", visual: sb('BARBADE', 'GRENADE', 'BRB', 'GRN', BRB, GRN, 2, 2, 'h', 'CSC') },
        { kicker: '3 MINUTES SURRÉALISTES', caption: 'Grenade attaque les *DEUX buts*.\nLa Barbade défend les *DEUX buts*.', voice: "Grenade comprend aussitôt : n'importe quel but, dans n'importe quelle cage, la qualifie. Alors Grenade attaque les deux buts… et la Barbade défend les deux buts. Pendant trois minutes surréalistes.", capSize: 64, visual: { type: 'pitch', mode: 'both', top: 'LA BARBADE DÉFEND LES DEUX', bottom: 'GRENADE ATTAQUE LES DEUX BUTS' } },
        { kicker: 'PROLONGATION · 94e', caption: '*But en or*. Barbade.\nCompte double : *4–2*.', voice: 'Prolongation. Quatrième minute. La Barbade marque le but en or. Il compte double : quatre à deux. La Barbade est qualifiée.', visual: sb('BARBADE', 'GRENADE', 'BRB', 'GRN', BRB, GRN, 4, 2, 'h', 'BUT EN OR'), glow: 'gold' },
        { kicker: "L'ENTRAÎNEUR DE GRENADE", caption: '« Celui qui a inventé\nces règles mérite\nune place à l\'asile. »', voice: "L'entraîneur de Grenade dira : celui qui a inventé ces règles mérite une place à l'asile.", capSize: 66, visual: { type: 'quote' } },
        { kicker: 'À VOUS', caption: 'Vous auriez fait\n*PAREIL* ?', voice: "Vous auriez fait pareil ? Dites-le-nous en commentaire, et abonnez-vous à Pressing quatre-vingt-dix pour d'autres histoires incroyables du foot. L'histoire complète sur pressing quatre-vingt-dix point live.", visual: { type: 'cta' }, glow: 'gold', min: 10 },
      ],
      article: [
        "Le 27 janvier 1994, en qualifications de la Shell Caribbean Cup, la Barbade reçoit Grenade avec une consigne simple : gagner par au moins deux buts d'écart pour rejoindre la phase finale. À défaut, c'est Grenade qui passe.",
        "Le tournoi applique une règle qui paraît anodine : en cas d'égalité, prolongation, et un but en or en prolongation compte double. Personne n'imagine ce qu'elle permet.",
        "La Barbade mène 2–0 jusqu'à la 83e minute, quand Grenade réduit le score. À 2–1, la Barbade gagne le match mais perd la qualification. Marquer un troisième but en quelques minutes semble impossible, alors les joueurs barbadiens prennent une décision qui sidère encore aujourd'hui : à trois minutes de la fin, ils marquent volontairement contre leur camp. À 2–2, il y aura prolongation, et un but en or vaudra deux buts.",
        "Grenade comprend en quelques secondes. Un but dans n'importe quelle cage la qualifie désormais : un but normal pour gagner 3–2, ou un but contre son camp pour perdre d'un seul but, ce qui suffit. Pendant les dernières minutes, Grenade attaque donc les deux buts pendant que la Barbade défend les deux, la séquence la plus étrange jamais vue en match international officiel.",
        "La Barbade tient, et à la quatrième minute de la prolongation marque le but en or. Compté double, le résultat est enregistré 4–2 et la Barbade se qualifie. L'entraîneur de Grenade, James Clarkson, ne cache pas sa colère : celui qui a inventé ces règles, dit-il, mérite une place à l'asile. La règle n'a jamais été réutilisée.",
      ],
    },
    ar: {
      title: 'اليوم الذي سجّلت فيه باربادوس في مرماها لتفوز',
      hook: 'فريق سجّل في مرماه… عمدًا. ليفوز بالمباراة.',
      question: '🤔 هل كنت ستسجّل ذلك الهدف في مرماك؟ نعم أم لا، ولماذا؟ 👇',
      caption: 'سجّلوا في مرماهم عمدًا… ونجحت الخطة! 🤯\nأغرب ثلاث دقائق في تاريخ كرة القدم، في 90 ثانية ⬇️',
      excerpt: 'كأس الكاريبي، يناير 1994: باربادوس تسجّل عمدًا في مرماها، غرينادا تهاجم المرميين، والهدف الذهبي يُحتسب هدفين. أغرب ثلاث دقائق في كرة القدم الدولية.',
      hashtags: '#كرة_القدم #قصص_كرة_القدم #هل_تعلم #Pressing90',
      beats: [
        { kicker: 'هل تعلم؟', caption: 'فريق سجّل *في مرماه*…\n*عمدًا*.\n*ليفوز* بالمباراة!', voice: 'هل تعلم؟ في يومٍ من الأيام، سجّل فريقُ كرة قدم هدفًا في مرماه… عمدًا… ليفوز بالمباراة.', visual: { type: 'mark', text: '?', color: 'green' }, glow: 'gold', capSize: 84, min: 4 },
        { kicker: 'يناير 1994', caption: 'تصفيات\nكأس الكاريبي', voice: 'يناير 1994. تصفيات كأس الكاريبي. باربادوس ضد غرينادا.', visual: sb('باربادوس', 'غرينادا', 'BRB', 'GRN', BRB, GRN, 0, 0) },
        { kicker: 'المعادلة', caption: 'على باربادوس أن تفوز\n*بفارق هدفين*.\nوإلا تتأهل *غرينادا*.', voice: 'كان على باربادوس أن تفوز بفارق هدفين. أقل من ذلك، وتتأهل غرينادا.', capSize: 74 },
        { kicker: 'الدقيقة 83', caption: '*غرينادا* تسجّل.\nباربادوس *خارج البطولة*!', voice: 'تقدّمت باربادوس بهدفين دون رد. ثم في الدقيقة 83 سجّلت غرينادا. اثنان لواحد. باربادوس خارج البطولة.', visual: sb('باربادوس', 'غرينادا', 'BRB', 'GRN', BRB, GRN, 2, 1, 'a') },
        { kicker: 'القاعدة المجنونة', caption: '*الهدف الذهبي* في الوقت الإضافي\n= *هدفان*!', voice: 'لكن هذه البطولة كانت فيها قاعدة مجنونة: الهدف الذهبي في الوقت الإضافي يُحتسب هدفين.', visual: { type: 'mark', text: '×2', color: 'gold' }, glow: 'gold' },
        { kicker: 'الدقيقة 87', caption: 'باربادوس تسجّل…\n*في مرماها*!', voice: 'فقبل ثلاث دقائق من النهاية، فعلت باربادوس ما لا يُصدَّق. استدارت… وسجّلت في مرماها. اثنان لاثنين.', visual: sb('باربادوس', 'غرينادا', 'BRB', 'GRN', BRB, GRN, 2, 2, 'h', 'هدف عكسي') },
        { kicker: 'ثلاث دقائق لا تُصدَّق', caption: 'غرينادا تهاجم *المرميين*.\nباربادوس تدافع عن *المرميين*.', voice: 'فهمت غرينادا فورًا: أيّ هدف، في أيّ مرمى، يؤهّلها. فهاجمت غرينادا المرميين… ودافعت باربادوس عن المرميين. ثلاث دقائق لا تُصدَّق.', capSize: 62, visual: { type: 'pitch', mode: 'both', top: 'باربادوس تدافع عن المرميين', bottom: 'غرينادا تهاجم المرميين' } },
        { kicker: 'الوقت الإضافي · 94', caption: '*هدف ذهبي*. باربادوس.\nيُحتسب هدفين: *4–2*', voice: 'الوقت الإضافي. الدقيقة الرابعة. سجّلت باربادوس الهدف الذهبي. احتُسب هدفين: أربعة لاثنين. باربادوس تتأهل.', visual: sb('باربادوس', 'غرينادا', 'BRB', 'GRN', BRB, GRN, 4, 2, 'h', 'هدف ذهبي'), glow: 'gold' },
        { kicker: 'مدرّب غرينادا', caption: '«من اخترع هذه القواعد\nيستحق مكانًا\nفي مستشفى المجانين»', voice: 'قال مدرّب غرينادا: من اخترع هذه القواعد يستحق مكانًا في مستشفى المجانين.', capSize: 64, visual: { type: 'quote' } },
        { kicker: 'دورك', caption: 'هل كنت ستفعل\n*الشيء نفسه*؟', voice: 'هل كنت ستفعل الشيء نفسه؟ أخبرنا في التعليقات، وتابع بريسينغ تسعين لمزيد من قصص كرة القدم المذهلة. القصة كاملة على موقع بريسينغ تسعين دوت لايف.', visual: { type: 'cta' }, glow: 'gold', min: 10 },
      ],
      article: [
        'في 27 يناير 1994، وفي تصفيات كأس الكاريبي، استضافت باربادوس منتخب غرينادا بمهمّة تبدو بسيطة: الفوز بفارق هدفين على الأقل لبلوغ النهائيات. وأيّ نتيجة أخرى تؤهّل غرينادا.',
        'اعتمدت البطولة قاعدة بدت بريئة: عند التعادل يُلعب وقت إضافي، والهدف الذهبي في الوقت الإضافي يُحتسب هدفين. لم يتخيّل أحد كيف يمكن استغلالها.',
        'تقدّمت باربادوس 2–0 حتى الدقيقة 83 حين قلّصت غرينادا الفارق. بنتيجة 2–1 كانت باربادوس تفوز بالمباراة لكنها تخسر التأهّل. وبدا تسجيل هدف ثالث في الدقائق الأخيرة مستحيلًا، فاتّخذ لاعبو باربادوس قرارًا ما زال يذهل الجماهير: قبل ثلاث دقائق من النهاية سجّلوا عمدًا في مرماهم. بالتعادل 2–2 تذهب المباراة إلى الوقت الإضافي، حيث يُحتسب الهدف الذهبي هدفين.',
        'فهمت غرينادا الأمر في ثوانٍ: أيّ هدف في أيّ مرمى يؤهّلها الآن، هدف عادي يمنحها الفوز 3–2، أو هدف في مرماها يجعلها تخسر بفارق هدف واحد وهو ما يكفي. فهاجمت غرينادا المرميين في الدقائق الأخيرة بينما دافعت باربادوس عن المرميين، في أغرب مشهد شهدته مباراة دولية رسمية.',
        'صمدت باربادوس، وفي الدقيقة الرابعة من الوقت الإضافي سجّلت الهدف الذهبي. احتُسب هدفين، فسُجّلت النتيجة 4–2 وتأهّلت باربادوس. ولم يُخفِ مدرّب غرينادا جيمس كلاركسون غضبه: من اخترع هذه القواعد، قال، يستحق مكانًا في مستشفى المجانين. ولم تُستخدم القاعدة مرة أخرى.',
      ],
    },
  },
  // ───────────────────────────────────────────────────────────────────────
  {
    slug: 'pickles-the-dog-world-cup-1966',
    year: '1966',
    en: {
      title: 'The World Cup was stolen. A dog found it.',
      hook: 'The World Cup trophy was stolen… and found by a dog.',
      question: '🤔 Who is the real hero of 1966: Pickles or Bobby Moore? 😄👇',
      caption: 'The World Cup was stolen four months before the tournament. A dog found it. 🐶🏆\nThe full story in 90 seconds ⬇️',
      excerpt: 'March 1966: the Jules Rimet Trophy vanished from a London exhibition four months before the World Cup. A week later, a collie named Pickles found it under a hedge.',
      hashtags: '#football #footballstories #WorldCup #didyouknow #Pressing90',
      beats: [
        { kicker: 'DID YOU KNOW?', caption: 'The World Cup trophy\nwas STOLEN…\nand found by a DOG.', voice: 'Did you know… the World Cup trophy was once stolen… and found by a dog?', visual: { type: 'mark', text: '?', color: 'green' }, glow: 'gold', capSize: 90, min: 4 },
        { kicker: 'MARCH 1966 · LONDON', image: { query: 'Jules Rimet Trophy' }, caption: 'The Jules Rimet Trophy\non public display\nat a stamp exhibition.', voice: 'March 1966. London. Four months before the World Cup, the Jules Rimet Trophy is on public display at a stamp exhibition.', visual: { type: 'mark', text: '1966', color: 'gold' }, capSize: 76 },
        { kicker: 'SUNDAY 20 MARCH', image: { query: 'Methodist Central Hall Westminster' }, caption: 'Stolen in broad daylight.\nThe guards saw NOTHING.', voice: 'Sunday, the twentieth of March. In broad daylight, the trophy vanishes from its glass case. The guards saw nothing.', visual: { type: 'mark', text: '!', color: 'gold' }, glow: 'gold' },
        { kicker: 'THE RANSOM', caption: 'A note demands £15,000.\nA man is arrested…\nbut NO trophy.', voice: 'Two days later, a ransom note arrives: fifteen thousand pounds for the cup. Police set a trap, a man is arrested… but the trophy is still missing.', visual: { type: 'mark', text: '£15,000', color: 'gold' }, capSize: 76 },
        { kicker: 'SUNDAY 27 MARCH', image: { query: 'Beulah Hill Upper Norwood London' }, caption: 'South London.\nDavid Corbett walks\nhis dog, Pickles.', voice: 'A week later, in south London, a man named David Corbett takes his dog Pickles out for an evening walk.', visual: { type: 'mark', text: 'PICKLES', color: 'green' }, capSize: 76 },
        { kicker: 'UNDER A HEDGE', image: { query: 'border collie dog black and white' }, caption: 'Pickles sniffs a package\nwrapped in newspaper…', voice: "Pickles stops at a hedge and starts sniffing a package wrapped in newspaper. Corbett tears it open… and reads the names on the base: Brazil. West Germany. Uruguay.", visual: { type: 'mark', text: '?', color: 'green' } },
        { kicker: 'THE JULES RIMET TROPHY', caption: 'Found. By a dog.\nPickles becomes\na national HERO.', voice: "It's the World Cup. Found by a dog. Overnight, Pickles becomes a national hero.", visual: { type: 'mark', text: 'HERO', color: 'green' }, glow: 'gold' },
        { kicker: 'JULY 1966', image: { query: 'Wembley Stadium twin towers' }, caption: 'England win the World Cup.\nPickles is invited\nto the banquet.', voice: 'In July, England win the World Cup at Wembley. At the celebration banquet, one guest of honour walks in on four legs: Pickles.', visual: { type: 'mark', text: '1966', color: 'gold' }, capSize: 74 },
        { kicker: 'THE TWIST', image: { query: 'Rio de Janeiro Maracana stadium' }, caption: '1983, Rio de Janeiro:\nthe trophy is stolen AGAIN.\nNever found.', voice: 'The twist? In 1983, in Rio de Janeiro, the trophy was stolen again. This time, it was never found. Most believe it was melted down.', visual: { type: 'mark', text: '1983', color: 'gold' }, capSize: 74, glow: 'gold' },
        { kicker: 'YOUR TURN', caption: 'The real hero of 1966:\nPickles or Bobby Moore?', voice: "So who's the real hero of 1966: Pickles, or Bobby Moore? Tell us in the comments, and follow Pressing 90 for more incredible football stories. Full story on pressing ninety dot live.", visual: { type: 'cta' }, glow: 'gold', capSize: 74, min: 10 },
      ],
      article: [
        'In March 1966, four months before England hosted the World Cup, the Jules Rimet Trophy was lent to a stamp exhibition at Central Hall in Westminster, London, and shown in a glass case under guard. On Sunday 20 March, in the middle of the day, it disappeared. The guards had seen nothing.',
        "The Football Association received a ransom demand of £15,000. Police organised a hand-over, arrested the man who turned up, and still had no trophy. The embarrassment was total: the world's most famous football prize had been lost by the country about to host the tournament.",
        'On Sunday 27 March, David Corbett took his collie, Pickles, for an evening walk in Beulah Hill, south London. Pickles stopped at a hedge and started sniffing a package wrapped in newspaper. Corbett tore it open and read the names engraved on the base: Brazil, West Germany, Uruguay. It was the World Cup.',
        'Pickles became a national celebrity overnight. Corbett received a reward worth several times the bonus England players would earn for winning the tournament, and when England lifted the trophy at Wembley in July, Pickles was invited to the celebration banquet.',
        'The trophy itself had a darker ending. Awarded permanently to Brazil after their third title in 1970, it was stolen again in Rio de Janeiro in 1983 and never recovered. It is widely believed to have been melted down.',
      ],
    },
    fr: {
      title: 'La Coupe du monde a été volée. Un chien l\'a retrouvée.',
      hook: 'Le trophée de la Coupe du monde a été volé… et retrouvé par un chien.',
      question: '🤔 Le vrai héros de 1966 : Pickles ou Bobby Moore ? 😄👇',
      caption: 'La Coupe du monde volée quatre mois avant le tournoi. Retrouvée par un chien. 🐶🏆\nL\'histoire complète en 90 secondes ⬇️',
      excerpt: 'Mars 1966 : le trophée Jules-Rimet disparaît d\'une exposition à Londres, quatre mois avant la Coupe du monde. Une semaine plus tard, un colley nommé Pickles le retrouve sous une haie.',
      hashtags: '#football #histoiredufoot #CoupeDuMonde #lesaviezvous #Pressing90',
      beats: [
        { kicker: 'LE SAVIEZ-VOUS ?', caption: 'Le trophée de la Coupe\ndu monde a été *VOLÉ*…\net retrouvé par un *CHIEN*.', voice: 'Le saviez-vous ? Le trophée de la Coupe du monde a un jour été volé… et retrouvé par un chien.', visual: { type: 'mark', text: '?', color: 'green' }, glow: 'gold', capSize: 84, min: 4 },
        { kicker: 'MARS 1966 · LONDRES', image: { query: 'Jules Rimet Trophy' }, caption: 'Le *trophée Jules-Rimet*\nexposé au public\ndans un *salon de timbres*.', voice: 'Mars 1966. Londres. Quatre mois avant la Coupe du monde, le trophée Jules-Rimet est exposé au public dans un salon de philatélie.', visual: { type: 'mark', text: '1966', color: 'gold' }, capSize: 72 },
        { kicker: 'DIMANCHE 20 MARS', image: { query: 'Methodist Central Hall Westminster' }, caption: '*Volé* en plein jour.\nLes gardiens n\'ont *RIEN* vu.', voice: 'Dimanche 20 mars. En plein jour, le trophée disparaît de sa vitrine. Les gardiens n\'ont rien vu.', visual: { type: 'mark', text: '!', color: 'gold' }, glow: 'gold' },
        { kicker: 'LA RANÇON', caption: 'Une lettre réclame *15 000 £*.\nUn homme est *arrêté*…\nmais *PAS* de trophée.', voice: 'Deux jours plus tard, une demande de rançon arrive : quinze mille livres pour la coupe. La police tend un piège, un homme est arrêté… mais le trophée reste introuvable.', visual: { type: 'mark', text: '15 000 £', color: 'gold' }, capSize: 72 },
        { kicker: 'DIMANCHE 27 MARS', image: { query: 'Beulah Hill Upper Norwood London' }, caption: 'Sud de Londres.\nDavid Corbett promène\nson chien, *Pickles*.', voice: 'Une semaine plus tard, dans le sud de Londres, un certain David Corbett sort promener son chien Pickles.', visual: { type: 'mark', text: 'PICKLES', color: 'green' }, capSize: 74 },
        { kicker: 'SOUS UNE HAIE', image: { query: 'border collie dog black and white' }, caption: '*Pickles* renifle un *paquet*\nenveloppé dans du journal…', voice: 'Pickles s\'arrête devant une haie et renifle un paquet enveloppé dans du papier journal. Corbett le déchire… et lit les noms gravés sur le socle : Brésil. Allemagne de l\'Ouest. Uruguay.', visual: { type: 'mark', text: '?', color: 'green' }, capSize: 74 },
        { kicker: 'LE TROPHÉE JULES-RIMET', caption: '*Retrouvé*. Par un *chien*.\nPickles devient\nun *HÉROS* national.', voice: 'C\'est la Coupe du monde. Retrouvée par un chien. Du jour au lendemain, Pickles devient un héros national.', visual: { type: 'mark', text: 'HÉROS', color: 'green' }, glow: 'gold', capSize: 76 },
        { kicker: 'JUILLET 1966', image: { query: 'Wembley Stadium twin towers' }, caption: 'L\'Angleterre *gagne* la Coupe.\n*Pickles* est invité\nau *banquet*.', voice: 'En juillet, l\'Angleterre remporte la Coupe du monde à Wembley. Au banquet de célébration, un invité d\'honneur arrive sur quatre pattes : Pickles.', visual: { type: 'mark', text: '1966', color: 'gold' }, capSize: 72 },
        { kicker: 'LE RETOURNEMENT', image: { query: 'Rio de Janeiro Maracana stadium' }, caption: '*1983*, Rio de Janeiro :\nle trophée est volé *ENCORE*.\n*Jamais* retrouvé.', voice: 'Le retournement ? En 1983, à Rio de Janeiro, le trophée est volé à nouveau. Cette fois, il ne sera jamais retrouvé. On pense qu\'il a été fondu.', visual: { type: 'mark', text: '1983', color: 'gold' }, capSize: 72, glow: 'gold' },
        { kicker: 'À VOUS', caption: 'Le vrai héros de 1966 :\n*Pickles* ou *Bobby Moore* ?', voice: 'Alors, le vrai héros de 1966 : Pickles, ou Bobby Moore ? Dites-le-nous en commentaire, et abonnez-vous à Pressing quatre-vingt-dix pour d\'autres histoires incroyables du foot. L\'histoire complète sur pressing quatre-vingt-dix point live.', visual: { type: 'cta' }, glow: 'gold', capSize: 72, min: 10 },
      ],
      article: [
        'En mars 1966, quatre mois avant la Coupe du monde organisée en Angleterre, le trophée Jules-Rimet est prêté à une exposition philatélique au Central Hall de Westminster, à Londres, et présenté dans une vitrine sous surveillance. Le dimanche 20 mars, en pleine journée, il disparaît. Les gardiens n\'ont rien vu.',
        'La Fédération anglaise reçoit une demande de rançon de 15 000 livres. La police organise une remise, arrête l\'homme qui se présente… et n\'a toujours pas le trophée. L\'embarras est total : le pays qui s\'apprête à accueillir le tournoi a perdu le trophée le plus célèbre du football.',
        'Le dimanche 27 mars, David Corbett sort promener son colley, Pickles, à Beulah Hill, dans le sud de Londres. Pickles s\'arrête devant une haie et renifle un paquet enveloppé dans du papier journal. Corbett le déchire et lit les noms gravés sur le socle : Brésil, Allemagne de l\'Ouest, Uruguay. C\'est la Coupe du monde.',
        'Pickles devient une célébrité nationale du jour au lendemain. Corbett touche une récompense qui vaut plusieurs fois la prime promise aux joueurs anglais pour une victoire finale, et lorsque l\'Angleterre soulève le trophée à Wembley en juillet, Pickles est invité au banquet de célébration.',
        'Le trophée, lui, connaîtra une fin plus sombre. Attribué définitivement au Brésil après son troisième titre en 1970, il est volé à nouveau à Rio de Janeiro en 1983 et jamais retrouvé. On pense qu\'il a été fondu.',
      ],
    },
    ar: {
      title: 'سُرقت كأس العالم… وعثر عليها كلب',
      hook: 'كأس العالم سُرقت… وعثر عليها كلب.',
      question: '🤔 من البطل الحقيقي لعام 1966: بيكلز أم بوبي مور؟ 😄👇',
      caption: 'سُرقت كأس العالم قبل البطولة بأربعة أشهر… وعثر عليها كلب! 🐶🏆\nالقصة كاملة في 90 ثانية ⬇️',
      excerpt: 'مارس 1966: اختفت كأس جول ريميه من معرض في لندن قبل أربعة أشهر من كأس العالم. وبعد أسبوع، عثر عليها كلب اسمه بيكلز تحت سياج.',
      hashtags: '#كرة_القدم #قصص_كرة_القدم #كأس_العالم #هل_تعلم #Pressing90',
      beats: [
        { kicker: 'هل تعلم؟', caption: 'كأس العالم *سُرقت*…\nوعثر عليها\n*كلب*!', voice: 'هل تعلم؟ في يومٍ من الأيام سُرقت كأس العالم… وعثر عليها كلب.', visual: { type: 'mark', text: '?', color: 'green' }, glow: 'gold', capSize: 84, min: 4 },
        { kicker: 'مارس 1966 · لندن', image: { query: 'Jules Rimet Trophy' }, caption: '*كأس جول ريميه*\nمعروضة للجمهور\nفي *معرض للطوابع*.', voice: 'مارس 1966. لندن. قبل أربعة أشهر من كأس العالم، كانت كأس جول ريميه معروضة للجمهور في معرض للطوابع البريدية.', visual: { type: 'mark', text: '1966', color: 'gold' }, capSize: 70 },
        { kicker: 'الأحد 20 مارس', image: { query: 'Methodist Central Hall Westminster' }, caption: '*سُرقت* في وضح النهار.\nولم يرَ الحرّاس *شيئًا*!', voice: 'الأحد العشرون من مارس. في وضح النهار، اختفت الكأس من خزانتها الزجاجية. ولم يرَ الحرّاس شيئًا.', visual: { type: 'mark', text: '!', color: 'gold' }, glow: 'gold', capSize: 70 },
        { kicker: 'الفدية', caption: 'رسالة تطلب *15 ألف جنيه*.\n*اعتُقل* رجل…\nلكن *لا كأس*!', voice: 'بعد يومين، وصلت رسالة فدية: خمسة عشر ألف جنيه مقابل الكأس. نصبت الشرطة كمينًا، واعتُقل رجل… لكن الكأس ما زالت مفقودة.', visual: { type: 'mark', text: '£15,000', color: 'gold' }, capSize: 70 },
        { kicker: 'الأحد 27 مارس', image: { query: 'Beulah Hill Upper Norwood London' }, caption: 'جنوب لندن.\nديفيد كوربيت يتنزّه\nمع كلبه *بيكلز*.', voice: 'بعد أسبوع، في جنوب لندن، خرج رجل يُدعى ديفيد كوربيت ليتنزّه مع كلبه بيكلز في المساء.', visual: { type: 'mark', text: 'PICKLES', color: 'green' }, capSize: 70 },
        { kicker: 'تحت سياج', image: { query: 'border collie dog black and white' }, caption: '*بيكلز* يشمّ *طردًا*\nملفوفًا بورق الجرائد…', voice: 'توقّف بيكلز عند سياج وبدأ يشمّ طردًا ملفوفًا بورق الجرائد. مزّقه كوربيت… وقرأ الأسماء المنقوشة على القاعدة: البرازيل. ألمانيا الغربية. الأوروغواي.', visual: { type: 'mark', text: '?', color: 'green' }, capSize: 70 },
        { kicker: 'كأس جول ريميه', caption: '*عُثر عليها*. بفضل كلب.\nبيكلز يصبح\n*بطلًا قوميًا*!', voice: 'إنها كأس العالم. عثر عليها كلب. وبين ليلة وضحاها، أصبح بيكلز بطلًا قوميًا.', visual: { type: 'mark', text: 'HERO', color: 'green' }, glow: 'gold', capSize: 70 },
        { kicker: 'يوليو 1966', image: { query: 'Wembley Stadium twin towers' }, caption: 'إنجلترا *تفوز* بكأس العالم.\nو*بيكلز* مدعوّ\nإلى *حفل التتويج*.', voice: 'في يوليو، فازت إنجلترا بكأس العالم في ويمبلي. وفي حفل الاحتفال، دخل ضيف شرف يمشي على أربع: بيكلز.', visual: { type: 'mark', text: '1966', color: 'gold' }, capSize: 68 },
        { kicker: 'المفاجأة', image: { query: 'Rio de Janeiro Maracana stadium' }, caption: '*1983*، ريو دي جانيرو:\n*سُرقت* الكأس مرة أخرى.\nولم يُعثر عليها *أبدًا*.', voice: 'المفاجأة؟ في عام 1983، في ريو دي جانيرو، سُرقت الكأس مرة أخرى. وهذه المرة لم يُعثر عليها أبدًا. ويُعتقد أنها صُهرت.', visual: { type: 'mark', text: '1983', color: 'gold' }, capSize: 66, glow: 'gold' },
        { kicker: 'دورك', caption: 'البطل الحقيقي لعام 1966:\n*بيكلز* أم *بوبي مور*؟', voice: 'إذن، من البطل الحقيقي لعام 1966: بيكلز أم بوبي مور؟ أخبرنا في التعليقات، وتابع بريسينغ تسعين لمزيد من قصص كرة القدم المذهلة. القصة كاملة على موقع بريسينغ تسعين دوت لايف.', visual: { type: 'cta' }, glow: 'gold', capSize: 68, min: 10 },
      ],
      article: [
        'في مارس 1966، قبل أربعة أشهر من كأس العالم التي استضافتها إنجلترا، أُعيرت كأس جول ريميه إلى معرض للطوابع في قاعة سنترال هول بويستمنستر في لندن، وعُرضت في خزانة زجاجية تحت الحراسة. وفي يوم الأحد 20 مارس، في منتصف النهار، اختفت. ولم يرَ الحرّاس شيئًا.',
        'تلقّى الاتحاد الإنجليزي طلب فدية بقيمة 15 ألف جنيه. نظّمت الشرطة عملية تسليم، واعتقلت الرجل الذي حضر، لكنها لم تجد الكأس. كان الإحراج كاملًا: البلد الذي يستعدّ لاستضافة البطولة أضاع أشهر جائزة في كرة القدم.',
        'وفي يوم الأحد 27 مارس، خرج ديفيد كوربيت ليتنزّه مساءً مع كلبه من فصيلة الكولي، بيكلز، في حيّ بيولا هيل جنوب لندن. توقّف بيكلز عند سياج وبدأ يشمّ طردًا ملفوفًا بورق الجرائد. مزّقه كوربيت وقرأ الأسماء المنقوشة على القاعدة: البرازيل، ألمانيا الغربية، الأوروغواي. كانت كأس العالم.',
        'أصبح بيكلز نجمًا قوميًا بين ليلة وضحاها. وحصل كوربيت على مكافأة تعادل أضعاف المنحة التي وُعد بها لاعبو إنجلترا في حال الفوز بالبطولة، وعندما رفعت إنجلترا الكأس في ويمبلي في يوليو، دُعي بيكلز إلى حفل الاحتفال.',
        'أما الكأس نفسها فكانت نهايتها أكثر قتامة. فبعد أن مُنحت للبرازيل بشكل دائم إثر لقبها الثالث عام 1970، سُرقت مرة أخرى في ريو دي جانيرو عام 1983 ولم يُعثر عليها قط. ويُعتقد على نطاق واسع أنها صُهرت.',
      ],
    },
  },
  // ───────────────────────────────────────────────────────────────────────
  {
    slug: 'estonia-scotland-1996-three-second-match',
    year: '1996',
    en: {
      title: 'The international match that lasted three seconds',
      hook: 'An international match that lasted three seconds.',
      question: '🤔 Should Scotland have been given the 3–0 win? Yes or no? 👇',
      caption: 'An international match that lasted three seconds. Not a typo. ⏱️\nWhat happened next is even stranger ⬇️',
      excerpt: 'Tallinn, October 1996: a row over floodlights, a kick-off moved to the afternoon, and Estonia stayed at the hotel. Scotland kicked off alone, and the referee blew after three seconds.',
      hashtags: '#football #footballstories #Scotland #didyouknow #Pressing90',
      beats: [
        { kicker: 'DID YOU KNOW?', caption: 'An international match\nthat lasted\nTHREE SECONDS.', voice: 'Did you know… an international football match once lasted… three seconds?', visual: { type: 'mark', text: '3 s', color: 'green' }, glow: 'gold', capSize: 92, min: 4 },
        { kicker: 'OCTOBER 1996 · TALLINN', image: { query: 'Kadriorg Stadium Tallinn' }, caption: 'World Cup qualifier.\nEstonia v Scotland.', voice: 'October 1996. Tallinn, Estonia. A World Cup qualifier against Scotland.', visual: sb('ESTONIA', 'SCOTLAND', 'EST', 'SCO', EST, SCO, 0, 0) },
        { kicker: 'THE DAY BEFORE', caption: 'Scotland complain:\nthe temporary floodlights\nare too WEAK.', voice: 'The day before, Scotland complain: the temporary floodlights are too weak for an evening game.', visual: { type: 'mark', text: '?', color: 'gold' }, capSize: 76 },
        { kicker: "FIFA'S DECISION", caption: 'Kick-off moved\nfrom 18:45 to 15:00.\nSame day.', voice: 'FIFA agrees and moves the kick-off from 18:45… to 15:00. Same day.', visual: { type: 'mark', text: '15:00', color: 'gold' }, glow: 'gold', capSize: 78 },
        { kicker: "ESTONIA'S ANSWER", caption: '“We are not coming.”', voice: "Estonia's answer: we are not coming. The players stay at their hotel.", visual: { type: 'mark', text: 'NO', color: 'gold' }, capSize: 90 },
        { kicker: '15:00', caption: 'Scotland walk out.\nThe referee blows.\nJohn Collins kicks off.', voice: 'Three o\'clock. Scotland walk out alone. The referee blows his whistle. John Collins taps the ball to a team-mate.', visual: { type: 'pitch', mode: 'one', top: 'SCOTLAND', bottom: '… AND NOBODY ELSE' }, capSize: 74 },
        { kicker: '3 SECONDS LATER', caption: 'Whistle. Match over.\n“One team in Tallinn.”', voice: 'Three seconds later, the referee blows again. Match over. The Scottish fans sing: one team in Tallinn.', visual: { type: 'mark', text: '3 s', color: 'green' }, glow: 'gold', capSize: 78 },
        { kicker: 'THE VERDICT', caption: 'Scotland expected a 3–0 win.\nFIFA ordered a REPLAY.', voice: 'Scotland expected a three–nil win. FIFA ordered a replay on neutral ground instead.', visual: sb('ESTONIA', 'SCOTLAND', 'EST', 'SCO', EST, SCO, '–', '–', undefined, 'REPLAY'), capSize: 70 },
        { kicker: 'FEBRUARY 1997 · MONACO', image: { query: 'Stade Louis II Monaco' }, caption: 'The replay: 0–0.\nThe shortest match ever\nhad the LONGEST story.', voice: 'Four months later in Monaco, the replay ends nil–nil. The shortest match ever… had the longest story.', visual: sb('ESTONIA', 'SCOTLAND', 'EST', 'SCO', EST, SCO, 0, 0, undefined, 'MONACO'), capSize: 70 },
        { kicker: 'YOUR TURN', caption: 'Should Scotland have been\ngiven the 3–0 win?', voice: 'Should Scotland have been given the three–nil win? Tell us in the comments, and follow Pressing 90 for more incredible football stories. Full story on pressing ninety dot live.', visual: { type: 'cta' }, glow: 'gold', capSize: 74, min: 10 },
      ],
      article: [
        'On 9 October 1996, Estonia were due to host Scotland in Tallinn in a qualifier for the 1998 World Cup. The evening before, the Scottish delegation inspected the temporary floodlights installed at the Kadriorg Stadium and complained that they were not good enough for an evening kick-off.',
        'FIFA sided with Scotland and, on the morning of the game, moved the kick-off from 18:45 to 15:00. The Estonian federation refused to accept a decision taken hours before the match, and the Estonian team stayed away.',
        'At three o\'clock Scotland walked out alone, in front of their own travelling supporters. The referee blew his whistle, John Collins played the ball to a team-mate, and three seconds later the referee blew again to abandon the match. In the stands the Scottish fans sang "one team in Tallinn".',
        'Scotland expected a 3–0 walkover. FIFA decided otherwise: the match would be replayed on neutral ground. It took place in Monaco on 11 February 1997 and finished 0–0. Scotland still qualified for the 1998 World Cup; Estonia did not.',
        'Nearly thirty years on, the three-second match remains the shortest international fixture ever staged, and one of football\'s favourite pub-quiz answers.',
      ],
    },
    fr: {
      title: 'Le match international qui a duré trois secondes',
      hook: 'Un match international qui a duré trois secondes.',
      question: '🤔 L\'Écosse aurait-elle dû obtenir la victoire 3–0 sur tapis vert ? Oui ou non ? 👇',
      caption: 'Un match international qui a duré trois secondes. Ce n\'est pas une faute de frappe. ⏱️\nLa suite est encore plus étrange ⬇️',
      excerpt: 'Tallinn, octobre 1996 : une dispute sur l\'éclairage, un coup d\'envoi avancé à l\'après-midi, et l\'Estonie qui reste à l\'hôtel. L\'Écosse engage seule, l\'arbitre siffle après trois secondes.',
      hashtags: '#football #histoiredufoot #Ecosse #lesaviezvous #Pressing90',
      beats: [
        { kicker: 'LE SAVIEZ-VOUS ?', caption: 'Un match international\nqui a duré\n*TROIS SECONDES*.', voice: 'Le saviez-vous ? Un match international de football a un jour duré… trois secondes.', visual: { type: 'mark', text: '3 s', color: 'green' }, glow: 'gold', capSize: 88, min: 4 },
        { kicker: 'OCTOBRE 1996 · TALLINN', image: { query: 'Kadriorg Stadium Tallinn' }, caption: 'Qualifications *Coupe du monde*.\n*Estonie* – *Écosse*.', voice: 'Octobre 1996. Tallinn, en Estonie. Un match de qualification pour la Coupe du monde contre l\'Écosse.', visual: sb('ESTONIE', 'ÉCOSSE', 'EST', 'SCO', EST, SCO, 0, 0), capSize: 72 },
        { kicker: 'LA VEILLE', caption: 'L\'Écosse se plaint :\nl\'*éclairage* provisoire\nest trop *FAIBLE*.', voice: 'La veille, l\'Écosse se plaint : l\'éclairage provisoire est trop faible pour jouer le soir.', visual: { type: 'mark', text: '?', color: 'gold' }, capSize: 74 },
        { kicker: 'LA DÉCISION DE LA FIFA', caption: 'Coup d\'envoi *avancé*\nde *18 h 45* à *15 h*.\nLe *jour même*.', voice: 'La FIFA avance le coup d\'envoi de 18 h 45… à 15 h. Le jour même.', visual: { type: 'mark', text: '15:00', color: 'gold' }, glow: 'gold', capSize: 76 },
        { kicker: 'LA RÉPONSE DE L\'ESTONIE', caption: '« On ne vient pas. »', voice: 'La réponse de l\'Estonie : on ne vient pas. Les joueurs restent à l\'hôtel.', visual: { type: 'mark', text: 'NON', color: 'gold' }, capSize: 88 },
        { kicker: '15 H', caption: 'L\'Écosse entre *seule*.\nL\'arbitre *siffle*.\nJohn Collins engage.', voice: 'Quinze heures. L\'Écosse entre seule sur le terrain. L\'arbitre siffle. John Collins donne le coup d\'envoi.', visual: { type: 'pitch', mode: 'one', top: 'ÉCOSSE', bottom: '… ET PERSONNE D\'AUTRE' }, capSize: 72 },
        { kicker: '3 SECONDES PLUS TARD', caption: 'Coup de sifflet. *Terminé*.\n« *One team in Tallinn*. »', voice: 'Trois secondes plus tard, l\'arbitre siffle à nouveau. Match terminé. Les supporters écossais chantent : one team in Tallinn.', visual: { type: 'mark', text: '3 s', color: 'green' }, glow: 'gold', capSize: 74 },
        { kicker: 'LE VERDICT', caption: 'L\'Écosse attendait un *3–0*.\nLa FIFA ordonne\nde *REJOUER*.', voice: 'L\'Écosse attendait un trois à zéro sur tapis vert. La FIFA ordonne de rejouer sur terrain neutre.', visual: sb('ESTONIE', 'ÉCOSSE', 'EST', 'SCO', EST, SCO, '–', '–', undefined, 'À REJOUER'), capSize: 70 },
        { kicker: 'FÉVRIER 1997 · MONACO', image: { query: 'Stade Louis II Monaco' }, caption: 'Le match rejoué : *0–0*.\nLe match le *plus court*\na eu la plus *LONGUE* suite.', voice: 'Quatre mois plus tard à Monaco, le match rejoué finit zéro à zéro. Le match le plus court… a eu la plus longue suite.', visual: sb('ESTONIE', 'ÉCOSSE', 'EST', 'SCO', EST, SCO, 0, 0, undefined, 'MONACO'), capSize: 66 },
        { kicker: 'À VOUS', caption: 'L\'Écosse méritait-elle\nle *3–0* sur tapis vert ?', voice: 'L\'Écosse méritait-elle la victoire trois à zéro sur tapis vert ? Dites-le-nous en commentaire, et abonnez-vous à Pressing quatre-vingt-dix pour d\'autres histoires incroyables du foot. L\'histoire complète sur pressing quatre-vingt-dix point live.', visual: { type: 'cta' }, glow: 'gold', capSize: 72, min: 10 },
      ],
      article: [
        'Le 9 octobre 1996, l\'Estonie doit recevoir l\'Écosse à Tallinn en qualifications pour la Coupe du monde 1998. La veille, la délégation écossaise inspecte l\'éclairage provisoire installé au stade Kadriorg et se plaint : il est insuffisant pour un match en soirée.',
        'La FIFA donne raison à l\'Écosse et, le matin même, avance le coup d\'envoi de 18 h 45 à 15 h. La fédération estonienne refuse une décision prise quelques heures avant le match, et l\'équipe estonienne ne se présente pas.',
        'À quinze heures, l\'Écosse entre seule sur la pelouse, devant ses propres supporters venus en déplacement. L\'arbitre siffle, John Collins passe le ballon à un coéquipier, et trois secondes plus tard l\'arbitre siffle à nouveau pour arrêter la rencontre. Dans les tribunes, les Écossais chantent « one team in Tallinn ».',
        'L\'Écosse s\'attend à une victoire 3–0 sur tapis vert. La FIFA en décide autrement : le match sera rejoué sur terrain neutre. Il a lieu à Monaco le 11 février 1997 et se termine 0–0. L\'Écosse se qualifiera tout de même pour la Coupe du monde 1998 ; l\'Estonie non.',
        'Près de trente ans plus tard, le match de trois secondes reste la rencontre internationale la plus courte jamais disputée, et l\'une des questions favorites des quiz de football.',
      ],
    },
    ar: {
      title: 'المباراة الدولية التي دامت ثلاث ثوانٍ',
      hook: 'مباراة دولية دامت ثلاث ثوانٍ فقط.',
      question: '🤔 هل كان يجب منح اسكتلندا الفوز 3–0؟ نعم أم لا؟ 👇',
      caption: 'مباراة دولية دامت ثلاث ثوانٍ فقط. ليس خطأً مطبعيًا. ⏱️\nوما حدث بعدها أغرب ⬇️',
      excerpt: 'تالين، أكتوبر 1996: خلاف حول الإضاءة، وموعد انطلاق قُدِّم إلى فترة الظهيرة، وإستونيا بقيت في الفندق. اسكتلندا بدأت المباراة وحدها، والحكم أطلق صافرته بعد ثلاث ثوانٍ.',
      hashtags: '#كرة_القدم #قصص_كرة_القدم #اسكتلندا #هل_تعلم #Pressing90',
      beats: [
        { kicker: 'هل تعلم؟', caption: 'مباراة دولية\nدامت\n*ثلاث ثوانٍ* فقط!', voice: 'هل تعلم؟ في يومٍ من الأيام، دامت مباراة دولية في كرة القدم… ثلاث ثوانٍ فقط.', visual: { type: 'mark', text: '3 s', color: 'green' }, glow: 'gold', capSize: 84, min: 4 },
        { kicker: 'أكتوبر 1996 · تالين', image: { query: 'Kadriorg Stadium Tallinn' }, caption: 'تصفيات *كأس العالم*.\n*إستونيا* ضد *اسكتلندا*.', voice: 'أكتوبر 1996. تالين، إستونيا. مباراة في تصفيات كأس العالم ضد اسكتلندا.', visual: sb('إستونيا', 'اسكتلندا', 'EST', 'SCO', EST, SCO, 0, 0), capSize: 70 },
        { kicker: 'قبل المباراة بيوم', caption: 'اسكتلندا تشتكي:\n*الإضاءة* المؤقتة\n*ضعيفة جدًا*!', voice: 'قبل المباراة بيوم، اشتكت اسكتلندا: الإضاءة المؤقتة ضعيفة جدًا لمباراة مسائية.', visual: { type: 'mark', text: '?', color: 'gold' }, capSize: 70 },
        { kicker: 'قرار الفيفا', caption: '*تقديم* موعد المباراة\nمن *18:45* إلى *15:00*.\nفي *اليوم نفسه*!', voice: 'وافقت الفيفا وقدّمت الانطلاق من 18:45… إلى 15:00. في اليوم نفسه.', visual: { type: 'mark', text: '15:00', color: 'gold' }, glow: 'gold', capSize: 70 },
        { kicker: 'ردّ إستونيا', caption: '«لن نأتي.»', voice: 'كان ردّ إستونيا: لن نأتي. وبقي اللاعبون في فندقهم.', visual: { type: 'mark', text: 'NO', color: 'gold' }, capSize: 90 },
        { kicker: 'الساعة 15:00', caption: 'اسكتلندا تدخل الملعب *وحدها*.\nالحكم يطلق *صافرته*.\nجون كولينز يبدأ المباراة.', voice: 'الثالثة بعد الظهر. دخلت اسكتلندا الملعب وحدها. أطلق الحكم صافرته. ومرّر جون كولينز الكرة إلى زميله.', visual: { type: 'pitch', mode: 'one', top: 'اسكتلندا', bottom: '… ولا أحد غيرها' }, capSize: 64 },
        { kicker: 'بعد ثلاث ثوانٍ', caption: 'صافرة. *انتهت* المباراة.\n«*فريق واحد في تالين*»', voice: 'بعد ثلاث ثوانٍ، أطلق الحكم صافرته مجددًا. انتهت المباراة. وغنّى الاسكتلنديون: فريق واحد في تالين.', visual: { type: 'mark', text: '3 s', color: 'green' }, glow: 'gold', capSize: 70 },
        { kicker: 'الحكم النهائي', caption: 'اسكتلندا توقّعت فوزًا *3–0*.\nلكن الفيفا قرّرت\n*إعادة المباراة*!', voice: 'توقّعت اسكتلندا فوزًا بثلاثية نظيفة. لكن الفيفا قرّرت إعادة المباراة على أرض محايدة.', visual: sb('إستونيا', 'اسكتلندا', 'EST', 'SCO', EST, SCO, '–', '–', undefined, 'إعادة'), capSize: 66 },
        { kicker: 'فبراير 1997 · موناكو', image: { query: 'Stade Louis II Monaco' }, caption: 'المباراة المعادة: *0–0*.\n*أقصر مباراة* في التاريخ\nكانت لها *أطول قصة*.', voice: 'بعد أربعة أشهر في موناكو، انتهت الإعادة بالتعادل السلبي. أقصر مباراة في التاريخ… كانت لها أطول قصة.', visual: sb('إستونيا', 'اسكتلندا', 'EST', 'SCO', EST, SCO, 0, 0, undefined, 'موناكو'), capSize: 64 },
        { kicker: 'دورك', caption: 'هل كان يجب منح اسكتلندا\nالفوز *3–0*؟', voice: 'هل كان يجب منح اسكتلندا الفوز بثلاثية نظيفة؟ أخبرنا في التعليقات، وتابع بريسينغ تسعين لمزيد من قصص كرة القدم المذهلة. القصة كاملة على موقع بريسينغ تسعين دوت لايف.', visual: { type: 'cta' }, glow: 'gold', capSize: 68, min: 10 },
      ],
      article: [
        'في 9 أكتوبر 1996، كان من المقرّر أن تستضيف إستونيا منتخب اسكتلندا في تالين ضمن تصفيات كأس العالم 1998. وفي المساء السابق، عاين الوفد الاسكتلندي الإضاءة المؤقتة المركّبة في ملعب كادريورغ واشتكى من أنها غير كافية لمباراة مسائية.',
        'انحازت الفيفا إلى اسكتلندا، وفي صباح يوم المباراة قدّمت موعد الانطلاق من 18:45 إلى 15:00. ورفض الاتحاد الإستوني قرارًا اتُّخذ قبل المباراة بساعات، فلم يحضر المنتخب الإستوني.',
        'في الثالثة بعد الظهر دخلت اسكتلندا الملعب وحدها أمام مشجعيها الذين سافروا لمؤازرتها. أطلق الحكم صافرته، ومرّر جون كولينز الكرة إلى زميله، وبعد ثلاث ثوانٍ أطلق الحكم صافرته مجددًا معلنًا إلغاء المباراة. وفي المدرجات غنّى الاسكتلنديون: «فريق واحد في تالين».',
        'توقّعت اسكتلندا فوزًا 3–0 بقرار إداري. لكن الفيفا قرّرت غير ذلك: تُعاد المباراة على أرض محايدة. وأُقيمت في موناكو في 11 فبراير 1997 وانتهت بالتعادل السلبي. وتأهّلت اسكتلندا رغم ذلك إلى كأس العالم 1998، أما إستونيا فلا.',
        'وبعد قرابة ثلاثين عامًا، ما زالت مباراة الثواني الثلاث أقصر مباراة دولية أُقيمت على الإطلاق، وواحدة من أشهر أسئلة مسابقات كرة القدم.',
      ],
    },
  },
]

/**
 * Subject bank for the daily generator (Mehdi, 2026-09-11: one story per day).
 * Each brief is a verified fact sheet; the LLM turns it into the 10-beat
 * script and may add widely known context but never invents dates,
 * numbers or quotes. Used in order; KV remembers which ones are done.
 */
export const TALE_SUBJECTS: Array<{ id: string; subject: string; brief: string; tag?: 'barca' }> = [
  // ── Barça stories (Mehdi, 2026-09-13: the page's 5 150 followers came from a Barça fan page — one Barça story a week) ──
  { id: 'barca-remontada-2017', tag: 'barca', subject: 'Barcelona 6–1 PSG, the 2017 "remontada" (Champions League round of 16)', brief: 'First leg, 14 February 2017, Parc des Princes: PSG 4–0 Barcelona (Di María 18\' and 55\', Draxler 40\', Cavani 72\'). Second leg, 8 March 2017, Camp Nou: Barcelona 6–1 PSG. Scorers: Luis Suárez 3\', Layvin Kurzawa own goal 40\', Lionel Messi penalty 50\', Edinson Cavani 62\' for PSG, Neymar free kick 88\', Neymar penalty 90+1\', Sergi Roberto 90+5\'. Aggregate 6–5. First time in Champions League history that a team overturned a 4–0 first-leg deficit. Barcelona coach Luis Enrique, PSG coach Unai Emery, referee Deniz Aytekin. Barcelona were then eliminated by Juventus in the quarter-finals (0–3 away, 0–0 home).' },
  { id: 'ronaldinho-bernabeu-2005', tag: 'barca', subject: 'Ronaldinho applauded by Real Madrid fans at the Bernabéu (19 November 2005)', brief: 'La Liga, 19 November 2005, Santiago Bernabéu: Real Madrid 0–3 Barcelona. Scorers: Samuel Eto\'o 15\', Ronaldinho 59\' and 77\' (both after long solo runs). After his second goal, parts of the Real Madrid crowd stood and applauded Ronaldinho — a very rare tribute for a Barcelona player at the Bernabéu; the previous widely cited case is Diego Maradona in 1983 (Copa de la Liga). Ronaldinho received the Ballon d\'Or nine days later, on 28 November 2005. Barcelona coach Frank Rijkaard; Real Madrid coach Vanderlei Luxemburgo, sacked in December 2005. Barcelona won La Liga and the Champions League that season (2005–06).' },
  { id: 'wembley-1992', tag: 'barca', subject: 'Barcelona\'s first European Cup: Koeman\'s free kick at Wembley (20 May 1992)', brief: 'European Cup final, 20 May 1992, Wembley Stadium, London: Barcelona 1–0 Sampdoria after extra time. Goal: Ronald Koeman, direct free kick, 112th minute. Coach Johan Cruyff and the "Dream Team" (Zubizarreta, Koeman, Guardiola, Laudrup, Stoichkov, Bakero, Salinas). Before kick-off Cruyff told his players "Salid y disfrutad" ("Go out and enjoy yourselves"). Barcelona wore an orange kit that night. It was the club\'s first European Cup after the lost finals of 1961 (2–3 vs Benfica in Bern) and 1986 (on penalties vs Steaua București in Seville).' },
  { id: 'bernabeu-2-6-2009', tag: 'barca', subject: 'Real Madrid 2–6 Barcelona at the Bernabéu (2 May 2009)', brief: 'La Liga, 2 May 2009, Santiago Bernabéu: Real Madrid 2–6 Barcelona. Scorers for Barcelona: Thierry Henry 18\' and 58\', Carles Puyol 20\', Lionel Messi 35\' and 75\', Gerard Piqué 83\'; for Real Madrid: Gonzalo Higuaín 14\', Sergio Ramos 56\'. Pep Guardiola\'s first season as coach (2008–09); Real Madrid coach Juande Ramos. Barcelona went on to win La Liga, the Copa del Rey and the Champions League (2–0 vs Manchester United in Rome, 27 May 2009), then the Spanish Super Cup, the UEFA Super Cup and the Club World Cup: six trophies in 2009, the "sextuple".' },
  { id: 'manita-2010', tag: 'barca', subject: 'Barcelona 5–0 Real Madrid, the "manita" (29 November 2010)', brief: 'La Liga, 29 November 2010, Camp Nou: Barcelona 5–0 Real Madrid. Scorers: Xavi 10\', Pedro 18\', David Villa 55\' and 58\', Jeffrén 90+1\'. José Mourinho\'s first Clásico as Real Madrid coach; Pep Guardiola\'s Barcelona. Sergio Ramos was sent off in stoppage time after a foul on Messi and a shove on Puyol. Gerard Piqué held up five fingers ("manita") at the end. The scoreline repeated the 5–0 of Cruyff\'s Barcelona with Romário on 8 January 1994.' },
  { id: 'rivaldo-2001', tag: 'barca', subject: 'Rivaldo\'s hat-trick with a last-minute bicycle kick vs Valencia (17 June 2001)', brief: 'Last day of La Liga 2000–01, 17 June 2001, Camp Nou: Barcelona 3–2 Valencia. Barcelona needed a win to finish fourth and take the last Champions League place ahead of Valencia. Rivaldo scored all three goals: a free kick early in the first half, a long-range strike just before half-time, and in the 89th minute an overhead kick from the edge of the box after a headed pass by Frank de Boer. Valencia had equalised twice in between (1–1, 2–2). Rivaldo was the reigning 1999 Ballon d\'Or winner; coach Carles Rexach. Barcelona finished fourth and qualified for the Champions League.' },
  { id: 'messi-first-goal-2005', tag: 'barca', subject: 'Messi\'s first Barcelona goal, a lob assisted by Ronaldinho (1 May 2005)', brief: 'La Liga, 1 May 2005, Camp Nou: Barcelona 2–0 Albacete. Lionel Messi, aged 17 years 10 months and 7 days, came on for Samuel Eto\'o in the 87th minute. In stoppage time (90+1\') he lobbed goalkeeper Raúl Valbuena after a chipped pass from Ronaldinho, becoming at the time the youngest league scorer in Barcelona\'s history (record later beaten by Bojan in 2007, Ansu Fati in 2019 and Lamine Yamal in 2023). Moments earlier the same move had produced a goal disallowed for offside — Ronaldinho simply repeated the pass. Ronaldinho carried Messi on his back to celebrate. Messi\'s first-team debut had been in the derby against Espanyol on 16 October 2004, aged 17 years 3 months and 22 days.' },
  { id: 'lamine-yamal-records', tag: 'barca', subject: 'Lamine Yamal, the teenager who rewrote the record books (2023–2025)', brief: 'Born 13 July 2007 in Esplugues de Llobregat (Catalonia); Moroccan father, Equatoguinean mother; at La Masia from age 7. La Liga debut on 29 April 2023 against Real Betis aged 15 years and 290 days, the youngest player in Barcelona\'s La Liga history. First La Liga goal on 8 October 2023 against Granada aged 16 years and 87 days, then the youngest scorer in La Liga history. Spain debut on 8 September 2023 against Georgia aged 16 years and 57 days, scoring — the youngest player and scorer for Spain. Euro 2024: youngest player ever at a European Championship (16 years 338 days, Spain–Croatia, 15 June 2024) and youngest scorer in the tournament\'s history with the equaliser against France in the semi-final on 9 July 2024, aged 16 years and 362 days — the day before his 17th birthday; Spain beat England 2–1 in the final on 14 July 2024. Kopa Trophy (best under-21) at the 2024 Ballon d\'Or ceremony. Took Barcelona\'s number 10 shirt for 2025–26 after the 2024–25 La Liga, Copa del Rey and Supercopa treble.' },
  { id: 'athens-1994', tag: 'barca', subject: 'The night the Dream Team fell: Milan 4–0 Barcelona, Athens 1994', brief: 'Champions League final, 18 May 1994, Olympic Stadium, Athens: Milan 4–0 Barcelona. Scorers: Daniele Massaro 22\' and 45\', Dejan Savićević 47\' (a lob from the right), Marcel Desailly 58\'. Milan coach Fabio Capello was without the suspended Franco Baresi and Alessandro Costacurta. Cruyff\'s "Dream Team" (Romário, Stoichkov, Koeman, Guardiola, Laudrup left out of the squad) had just won a fourth consecutive La Liga title four days earlier, on 14 May 1994, when Deportivo\'s Miroslav Đukić missed a last-minute penalty against Valencia. Barcelona were the favourites; the defeat is seen as the end of the Dream Team era. Cruyff left the club in 1996.' },

  { id: 'camp-nou-1714', tag: 'barca', subject: 'Why Barcelona fans chant at minute 17:14 of every match (the 1714 chant)', brief: 'On 11 September 1714, after a siege of more than a year, the city of Barcelona fell to the troops of King Philip V during the War of the Spanish Succession; Catalonia then lost its own institutions and laws (the Nueva Planta decrees, 1716). 11 September is now the national day of Catalonia, the Diada. On 11 September 2012 a huge demonstration for Catalan independence filled Barcelona (more than one million people according to the organisers, the Assemblea Nacional Catalana). A few weeks later, at the Clásico Barcelona–Real Madrid played at the Camp Nou on 7 October 2012 (final score 2–2), thousands of fans stood up at 17 minutes and 14 seconds of the match and chanted "Independència" — 17:14 for the year 1714. Since then the chant is repeated at minute 17:14 of Barcelona matches, at the Camp Nou and often in away stadiums too. The estelada, the flag with a star used by supporters of independence, is common in the stands: in 2015 UEFA fined FC Barcelona 30,000 euros for the esteladas displayed by fans at the Champions League final in Berlin (6 June 2015), because UEFA bans political messages in its stadiums. The chant continues today, including at the Estadi Olímpic Lluís Companys where Barcelona played during the Camp Nou renovation.' },
  { id: 'yamal-messi-photo', tag: 'barca', subject: 'The 2007 charity photo of Lionel Messi bathing baby Lamine Yamal', brief: 'In December 2007, in Barcelona, Lionel Messi — then 20 years old and already a Barcelona star — took part in a charity photo shoot for a calendar made by the Barcelona sports newspaper Sport together with UNICEF; the photographer was Joan Monfort. Barcelona players posed with babies of local families chosen by a draw. Messi was photographed washing a baby in a small plastic tub. That baby was Lamine Yamal, born on 13 July 2007 in Esplugues de Llobregat near Barcelona, only a few months old. The photo resurfaced in 2024, shared by Yamal\'s father, Mounir Nasraoui, and went around the world. Lamine Yamal made his Barcelona first-team debut in April 2023 at 15, scored against France in the Euro 2024 semi-final on 9 July 2024 at 16 — the youngest scorer in the history of the European Championship — and won Euro 2024 with Spain on 14 July 2024 at 17. Since the 2025–26 season he wears the Barcelona number 10 shirt.' },
  { id: 'ben-barek', subject: 'Larbi Ben Barek, the "Black Pearl": the Moroccan who dazzled Europe before Pelé (1938–1954)', brief: 'Larbi Ben Barek was born in Casablanca, Morocco, on 16 June 1914 (some sources say 1917) and died in Casablanca on 16 September 1992. Nickname: "La Perle Noire" (the Black Pearl). He started at USM Casablanca in the mid-1930s. In 1938 he signed for Olympique de Marseille in France. On 4 December 1938, in Naples, he played his first match for the France national team against Italy (Italy won 1–0). After the Second World War he played for Stade Français in Paris (1945–1948), then for Atlético Madrid in Spain (1948–1953), where he won the Spanish league title twice (1949–50 and 1950–51). He returned to Marseille in 1953. He played 17 matches for France between 1938 and 1954 and scored 3 goals; his last match for France was on 16 October 1954 against West Germany, when he was 40 years old — a 16-year international career, a record for France at the time. Pelé is widely quoted as saying: "If I am the king of football, then Ben Barek is the god." In September 1992 he died alone in his home in Casablanca; his body was found several days later. In 1998 FIFA awarded him its Order of Merit posthumously.' },
  { id: 'ali-dia-1996', subject: 'Ali Dia, the fake "cousin of George Weah" who played in the Premier League (Southampton, 1996)', brief: 'November 1996. Southampton manager Graeme Souness took a phone call from a man claiming to be George Weah (FIFA World Player of the Year 1995), recommending his "cousin" Ali Dia, a Senegalese striker who had supposedly played for Paris Saint-Germain and Senegal. Souness signed Dia on a one-month contract. On 23 November 1996 against Leeds United, Dia came on as a substitute for Matt Le Tissier after 32 minutes, was himself substituted after 53 minutes on the pitch, and Southampton lost 2–0. The call was a hoax; the "cousin" had never played for PSG or Senegal. Dia was released after 14 days and later played for non-league Gateshead. Le Tissier later said Dia "ran around the pitch like Bambi on ice".' },
  { id: 'adema-149-0', subject: 'AS Adema 149–0 SO l\'Emyrne, the highest score in football history (Madagascar, 2002)', brief: '31 October 2002, Antananarivo, Madagascar, final round of the THB Champions League play-off. SO l\'Emyrne (SOE) were protesting a refereeing decision in their previous match that had cost them the title. From kick-off, SOE players deliberately scored own goal after own goal while Adema players stood and watched; the final score was 149–0, all own goals. The Guinness World Records lists it as the highest scoreline in a football match. The Malagasy federation suspended SOE coach Zaka Be for three years and banned four players for the rest of the season.' },
  { id: 'denmark-1992', subject: 'Denmark, called up ten days before Euro 1992, won the tournament', brief: 'Denmark had failed to qualify for Euro 1992, finishing second behind Yugoslavia. On 31 May 1992, Yugoslavia was excluded because of UN sanctions, and Denmark was invited as the replacement about ten days before the opening match. The story that the players were "on the beach" is a myth: they were already preparing for friendlies. Michael Laudrup chose not to play after a dispute with coach Richard Møller Nielsen. Denmark drew with England, lost to Sweden, beat France 2–1, beat the Netherlands on penalties in the semi-final (Peter Schmeichel saved Marco van Basten\'s kick), and beat Germany 2–0 in the final in Gothenburg on 26 June 1992 with goals from John Jensen and Kim Vilfort.' },
  { id: 'trautmann-1956', subject: 'Bert Trautmann played the last 17 minutes of the 1956 FA Cup final with a broken neck', brief: 'Bert Trautmann, a former German paratrooper and prisoner of war, became Manchester City\'s goalkeeper in 1949 despite initial protests from fans. In the FA Cup final on 5 May 1956 at Wembley against Birmingham City, with City leading 3–1, Trautmann dived at the feet of Peter Murphy in the 75th minute and was knocked out. He played on in obvious pain and made further saves; City won 3–1. Three days later an X-ray revealed he had broken a vertebra in his neck; he had played the last 17 minutes with a broken neck. He had been voted Footballer of the Year a week before the final.' },
  { id: 'two-balls-1930', subject: 'The 1930 World Cup final was played with two different balls', brief: 'The first World Cup final, 30 July 1930 at the Estadio Centenario in Montevideo, Uruguay against Argentina. The two teams could not agree on which ball to use, so it was decided to play the first half with the Argentine ball and the second half with the Uruguayan ball. Argentina led 2–1 at half-time with their ball; Uruguay scored three second-half goals with theirs and won 4–2. Uruguay became the first world champions.' },
  { id: 'coin-toss-1968', subject: 'Italy reached the Euro 1968 final on a coin toss', brief: 'Euro 1968 semi-final, 5 June 1968 in Naples: Italy 0–0 Soviet Union after extra time. Penalty shoot-outs did not exist yet, so the match was decided by a coin toss in the dressing room. Italy\'s captain Giacinto Facchetti called correctly and Italy went through. Italy then drew the final 1–1 with Yugoslavia and won the replay 2–0 two days later to become European champions. Penalty shoot-outs were introduced in 1970.' },
  { id: 'nayim-1995', subject: 'Nayim beat David Seaman from the halfway line in the 120th minute of a European final', brief: 'Cup Winners\' Cup final, 10 May 1995 in Paris, Real Zaragoza against Arsenal, 1–1 in the last minute of extra time. Zaragoza\'s Nayim, a former Tottenham player, received the ball around 40 metres from goal near the touchline and lobbed Arsenal goalkeeper David Seaman, who was off his line. The ball dropped under the crossbar in the 120th minute; Zaragoza won 2–1. Tottenham fans still sing about it because Nayim came from Spurs.' },
  { id: 'ireland-lots-1990', subject: 'Ireland\'s place at Italia 90 was decided by drawing lots', brief: 'World Cup 1990, Group F: the Republic of Ireland and the Netherlands finished level on points, goal difference, goals scored and their head-to-head result (1–1). FIFA drew lots on 21 June 1990: Ireland were placed second and the Netherlands third; both still advanced. Ireland then beat Romania on penalties in the round of 16 (Packie Bonner saved, David O\'Leary scored the winner) and reached the quarter-final, losing 1–0 to hosts Italy, at their first World Cup.' },
  { id: 'jimmy-glass-1999', subject: 'Jimmy Glass, the goalkeeper who scored in the 94th minute to save Carlisle from relegation', brief: '8 May 1999, last day of the English Third Division season. Carlisle United needed to beat Plymouth Argyle to stay in the Football League. Their goalkeeper Jimmy Glass was on a short emergency loan from Swindon Town because Carlisle had no fit keeper. With the score 1–1 in the fourth minute of stoppage time, Glass ran up for a corner and scored the winner from a rebound. Carlisle stayed up and Scarborough went down instead. Glass played only three games for Carlisle.' },
  { id: 'man-utd-1999', subject: 'Manchester United scored twice in stoppage time to win the 1999 Champions League final', brief: '26 May 1999, Camp Nou, Barcelona. Bayern Munich led Manchester United 1–0 through Mario Basler\'s sixth-minute free kick and hit the woodwork twice. Bayern\'s ribbons were already being tied to the trophy. Teddy Sheringham equalised in the first minute of stoppage time and Ole Gunnar Solskjær scored the winner in the third, both from David Beckham corners. United completed the treble (Premier League, FA Cup, Champions League). Sir Alex Ferguson said: "Football, bloody hell."' },
  { id: 'istanbul-2005', subject: 'The Miracle of Istanbul: Liverpool came back from 0–3 to win the 2005 Champions League final', brief: '25 May 2005, Atatürk Olympic Stadium, Istanbul. AC Milan led Liverpool 3–0 at half-time (Maldini after 50 seconds, Crespo twice). Liverpool scored three goals in six minutes after the break: Gerrard (54\'), Šmicer (56\') and Alonso (60\', rebound from his own saved penalty). Jerzy Dudek made a double save from Shevchenko in extra time and, wobbling his legs on the line, saved the decisive penalty from Shevchenko in the shoot-out. Liverpool won 3–2 on penalties, their fifth European Cup.' },
  { id: 'hand-of-god-1986', subject: 'The two most famous goals in one match: Maradona\'s Hand of God and the Goal of the Century', brief: 'World Cup quarter-final, 22 June 1986, Estadio Azteca, Mexico City, Argentina against England. In the 51st minute Diego Maradona punched the ball past goalkeeper Peter Shilton for the opening goal; Tunisian referee Ali Bin Nasser allowed it. Maradona said afterwards it was scored "a little with the head of Maradona and a little with the hand of God". Four minutes later he ran about 60 metres past five England players and Shilton to score what was later voted the Goal of the Century. Argentina won 2–1 and went on to win the World Cup.' },
  { id: 'wembley-1966-linesman', subject: 'The most disputed goal in World Cup history: the 1966 final', brief: 'World Cup final, 30 July 1966, Wembley, England against West Germany, 2–2 after 90 minutes. In the 101st minute Geoff Hurst\'s shot hit the underside of the crossbar and bounced down on or near the line. Swiss referee Gottfried Dienst consulted linesman Tofiq Bahramov, from Baku in the Soviet Union, who signalled a goal. England won 4–2, Hurst scoring the only hat-trick in a World Cup final. Scientific studies decades later concluded the ball probably did not fully cross the line. Azerbaijan\'s national stadium is named after Bahramov.' },
  { id: 'miracle-of-bern-1954', subject: 'The Miracle of Bern: unbeaten Hungary lost the 1954 World Cup final', brief: 'Hungary, with Ferenc Puskás, Sándor Kocsis and Nándor Hidegkuti, arrived at the 1954 World Cup unbeaten in four years, Olympic champions, and had thrashed West Germany 8–3 in the group stage. In the final on 4 July 1954 in Bern, in heavy rain, Hungary led 2–0 after eight minutes. West Germany equalised by the 18th minute and Helmut Rahn scored the winner in the 84th minute: 3–2. The German players wore adidas boots with screw-in studs, adapted to the muddy pitch. It was Hungary\'s only defeat in 51 matches between 1950 and 1956.' },
  { id: 'faroe-islands-1990', subject: 'The Faroe Islands beat Austria in their first ever competitive match', brief: '12 September 1990, Euro 1992 qualifier. The Faroe Islands, a group of islands with about 48,000 inhabitants and no grass pitch approved for international football, played their first competitive match in Landskrona, Sweden. Their part-time players, including goalkeeper Jens Martin Knudsen who wore a white bobble hat, beat Austria 1–0 with a goal by Torkil Nielsen, a timber salesman. It is still considered one of the biggest shocks in European football.' },
  { id: 'cameroon-1990', subject: 'Cameroon beat world champions Argentina with nine men in the opening match of Italia 90', brief: '8 June 1990, San Siro, Milan, opening match of the World Cup: Cameroon against reigning champions Argentina with Diego Maradona. François Omam-Biyik scored with a header in the 67th minute after a goalkeeping error by Nery Pumpido. Cameroon finished with nine men after two red cards (André Kana-Biyik and Benjamin Massing, whose foul on Claudio Caniggia became famous) and still won 1–0. With 38-year-old Roger Milla dancing at the corner flag after his goals, Cameroon became the first African team to reach a World Cup quarter-final, losing 3–2 to England after extra time.' },
  { id: 'greece-2004', subject: 'Greece won Euro 2004 at odds of 150 to 1', brief: 'Greece had never won a match at a major tournament before Euro 2004 in Portugal and were priced at around 150 to 1. Coached by German Otto Rehhagel with a disciplined defensive system, they beat hosts Portugal 2–1 in the opening match, then eliminated holders France 1–0 in the quarter-final (Angelos Charisteas) and the Czech Republic 1–0 in the semi-final with a silver goal by Traianos Dellas. In the final on 4 July 2004 in Lisbon they beat Portugal again, 1–0, with a Charisteas header. They won every knockout match 1–0.' },
  { id: 'saudi-argentina-2022', subject: 'Saudi Arabia beat Argentina at the 2022 World Cup and the kingdom declared a public holiday', brief: '22 November 2022, Lusail Stadium, Qatar. Argentina, unbeaten in 36 matches and eventual world champions, led 1–0 through a Lionel Messi penalty and had three goals disallowed for offside in the first half. Saudi Arabia scored twice in five minutes after the break, Saleh Al-Shehri (48\') and Salem Al-Dawsari (53\'), and won 2–1. It is rated one of the biggest upsets in World Cup history. The Saudi king declared the next day a national holiday.' },
  { id: 'morocco-2022', subject: 'Morocco 2022: the first African and Arab team in a World Cup semi-final', brief: 'At the 2022 World Cup in Qatar, Morocco, coached by Walid Regragui, who had been appointed only three months earlier, topped a group with Croatia and Belgium (beating Belgium 2–0), eliminated Spain on penalties in the round of 16 (goalkeeper Yassine Bounou saved two kicks, Achraf Hakimi scored the winning panenka) and beat Portugal 1–0 in the quarter-final with a Youssef En-Nesyri header. Morocco became the first African and first Arab team to reach a World Cup semi-final, losing 2–0 to France, and finished fourth. Sofyan Amrabat and the mothers of the players celebrating on the pitch became images of the tournament.' },
  { id: 'iceland-2016', subject: 'Iceland, a country of 330,000 people, knocked England out of Euro 2016', brief: 'Iceland, with a population of about 330,000, qualified for Euro 2016, their first major tournament, and were co-coached by Lars Lagerbäck and Heimir Hallgrímsson, a part-time dentist. In the round of 16 on 27 June 2016 in Nice, England took the lead through a Wayne Rooney penalty in the fourth minute; Ragnar Sigurdsson equalised two minutes later and Kolbeinn Sigthórsson scored the winner in the 18th minute. Iceland won 2–1. England manager Roy Hodgson resigned that night. Iceland\'s fans made the "thunderclap" chant famous.' },
  { id: 'gijon-1982', subject: 'The Disgrace of Gijón: the match that changed World Cup rules', brief: '25 June 1982, World Cup in Spain, last group match: West Germany against Austria in Gijón. Algeria had beaten West Germany and had already played their final game the day before. A West German win by one or two goals would send both West Germany and Austria through at Algeria\'s expense. Horst Hrubesch scored in the 10th minute and for the remaining 80 minutes both teams passed the ball around without attacking, to whistles from the crowd. Algeria\'s protest was rejected, but FIFA changed the rules: from 1986 the final group matches are played simultaneously.' },
  { id: 'roberto-carlos-1997', subject: 'Roberto Carlos\'s impossible free kick against France (1997)', brief: '3 June 1997, Tournoi de France in Lyon, France against Brazil. From about 35 metres, Roberto Carlos struck a free kick with the outside of his left foot; the ball swerved wide of the wall, appeared to be going well past the post, then curved back and went in off the inside of the post. A ball boy behind the goal ducked. Goalkeeper Fabien Barthez did not move. Physicists later studied the kick and explained the trajectory through the spin of the ball. The match ended 1–1.' },
  { id: 'senegal-france-2002', subject: 'Senegal beat world champions France in the opening match of the 2002 World Cup', brief: '31 May 2002, Seoul, opening match of the World Cup: France, reigning world and European champions, against Senegal, at their first World Cup, with most players in the French league. Papa Bouba Diop scored in the 30th minute after a run by El Hadji Diouf; Senegal won 1–0 and the players danced around Diop\'s shirt at the corner flag. France failed to score in the tournament and went out in the group stage; Senegal reached the quarter-final, losing to Turkey with a golden goal.' },
  { id: 'ronaldinho-bernabeu-2005', subject: 'The night the Bernabéu applauded Ronaldinho', brief: '19 November 2005, Santiago Bernabéu, Real Madrid against Barcelona. Barcelona won 3–0 with a goal by Samuel Eto\'o and two solo goals by Ronaldinho, in the 59th and 78th minutes, each time running from the halfway line past several defenders. After the second goal, sections of the Real Madrid crowd stood and applauded him, something the Bernabéu had done for a Barcelona player only for Diego Maradona in 1983. Ronaldinho won the Ballon d\'Or a week later.' },
]
